<!-- <p>本项目源码仓库<a href="https://github.com/Robust-Robot/DataBlockly" target="_blank">DataBlockly</a>，基于谷歌的Blockly实现。</p> -->

<div id="walkthrough-1">
    <h4>教程导航操作</h4>
    <p>点击右上角<image src='../../help/jquery-pagewalkthrough-dist/css/images/close.png'></image>直接关闭教程，<br>点击左箭头&larr;返回上一页。</p>
</div>

<div id="walkthrough-2">
    这是网站首页标题。
</div>
<div id="walkthrough-workspace">
    这里是工作区，从左边工具栏（云表仓库）中把各种块拖放入本区域，进行表设计。
</div>
<div id="walkthrough-blocksleft">
    如果锁定了可以添加的块数量，这里显示还剩下多少块。
</div>

<div id="walkthrough-btnbar">
    点击这些功能按钮，可以实现相应功能哦。
</div>
<div id="walkthrough-5">
    点击这些页标签，实现不同标签页的切换显示。<br>Blocks块积木：元件仓库；<br>JavaScript显示生成数据库表的SQL脚本语句；<br>XML显示的是块定义。
</div>
<div id="walkthrough-footer">
    这不用说啦，你懂的，是页脚和版权信息。<br>尊重和保护知识产权，从你我做起。
</div>
<div id="walkthrough-goodbye">
    好啦，愉快之旅就此结束。<br>更多惊喜等着你去发现哦，<br>感谢您的使用！
</div>
